"""Adicionando uma tabela de saída

Revision ID: 4b963c218db0
Revises: 230afdb0b770
Create Date: 2024-11-24 15:04:58.039293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b963c218db0'
down_revision = '230afdb0b770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('confirm_password',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('nivel_funcao',
               existing_type=sa.TEXT(length=15),
               type_=sa.String(length=15),
               existing_nullable=False,
               existing_server_default=sa.text('(comum)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('nivel_funcao',
               existing_type=sa.String(length=15),
               type_=sa.TEXT(length=15),
               existing_nullable=False,
               existing_server_default=sa.text('(comum)'))
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=False)
        batch_op.alter_column('confirm_password',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
